server:
  context-path: /ems  #指定项目名称
  port: 8080  #指定端口
  jsp-servlet:
    init-parameters:
      development: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
mybatis:
  mapper-locations: classpath:com/hbue/mapper/*.xml
  type-aliases-package: com.hbue.pojo
